export const VIBES = {
  neutral: {
    label: 'Neutral',
    mark: 'BASE',
    sub: 'original',
    audio: {
      tempo: 1,
      lowpass: 20000,
      highpass: 20,
      reverbWet: 0,
      bassGain: 0,
      midGain: 0,
      highGain: 0,
      distortion: 0,
      vinyl: 0,
      compression: 0,
    },
    visual: {
      feedbackAlpha: 0.92,
      modeOrder: ['Wave Terrain', 'Plasma Orb', 'Prism Void', 'Kinetic Cubes', 'Spectral Lattice', 'Water', 'Sand', 'Radial Bars', 'Linear Spectrum', 'Particle Field', 'Waveform Rings', 'Kaleidoscope'],
    },
    pitchLock: false,
    pitchReason: 'Tempo at 100% - no pitch shift either way.',
  },
  melancholic: {
    label: 'Melancholic',
    mark: 'RAIN',
    sub: 'slow + reverb',
    audio: {
      tempo: 0.82,
      lowpass: 7000,
      highpass: 60,
      reverbWet: 0.55,
      bassGain: -2,
      midGain: 1,
      highGain: -4,
      distortion: 0,
      vinyl: 0,
      compression: 0,
    },
    visual: { feedbackAlpha: 0.96, modeOrder: ['Wave Terrain', 'Waveform Rings', 'Water', 'Sand', 'Plasma Orb', 'Prism Void', 'Spectral Lattice'] },
    pitchLock: false,
    pitchReason: 'Off recommended. The slowed + reverb sound gets its weight from the natural pitch drop.',
  },
  edm: {
    label: 'High-Energy EDM',
    mark: 'EDM',
    sub: 'fast + punchy',
    audio: {
      tempo: 1.12,
      lowpass: 20000,
      highpass: 40,
      reverbWet: 0.12,
      bassGain: 5,
      midGain: 0,
      highGain: 3,
      distortion: 0.15,
      vinyl: 0,
      compression: 0.6,
    },
    visual: { feedbackAlpha: 0.86, modeOrder: ['Kinetic Cubes', 'Linear Spectrum', 'Plasma Orb', 'Kaleidoscope', 'Spectral Lattice', 'Prism Void', 'Wave Terrain', 'Particle Field'] },
    pitchLock: true,
    pitchReason: 'On recommended. Speed changes stay energetic without making vocals jump registers.',
  },
  lofi: {
    label: 'Lo-fi',
    mark: 'TAPE',
    sub: 'vinyl + muffled',
    audio: {
      tempo: 0.88,
      lowpass: 4500,
      highpass: 100,
      reverbWet: 0.25,
      bassGain: 2,
      midGain: -1,
      highGain: -6,
      distortion: 0.05,
      vinyl: 0.15,
      compression: 0.3,
    },
    visual: { feedbackAlpha: 0.94, modeOrder: ['Sand', 'Particle Field', 'Waveform Rings', 'Wave Terrain', 'Water', 'Plasma Orb', 'Prism Void', 'Spectral Lattice'] },
    pitchLock: false,
    pitchReason: 'Off recommended. A little pitch drop adds to the tape-warped warmth.',
  },
  reggae: {
    label: 'Reggae Dub',
    mark: 'DUB',
    sub: 'warm + wide reverb',
    audio: {
      tempo: 0.92,
      lowpass: 9000,
      highpass: 50,
      reverbWet: 0.4,
      bassGain: 4,
      midGain: 0,
      highGain: -2,
      distortion: 0,
      vinyl: 0,
      compression: 0.2,
    },
    visual: { feedbackAlpha: 0.93, modeOrder: ['Water', 'Radial Bars', 'Wave Terrain', 'Plasma Orb', 'Sand', 'Prism Void', 'Spectral Lattice'] },
    pitchLock: true,
    pitchReason: 'On recommended. The small tempo nudge keeps vocals natural while bass and space do the mood work.',
  },
  punk: {
    label: 'Rock / Punk',
    mark: 'PUNK',
    sub: 'distortion + bite',
    audio: {
      tempo: 1.05,
      lowpass: 20000,
      highpass: 80,
      reverbWet: 0.08,
      bassGain: 3,
      midGain: 4,
      highGain: 2,
      distortion: 0.55,
      vinyl: 0,
      compression: 0.7,
    },
    visual: { feedbackAlpha: 0.88, modeOrder: ['Kinetic Cubes', 'Linear Spectrum', 'Spectral Lattice', 'Prism Void', 'Plasma Orb', 'Kaleidoscope', 'Sand', 'Wave Terrain'] },
    pitchLock: true,
    pitchReason: 'On recommended. The aggression comes from drive and compression, not squeaky pitch changes.',
  },
  jazz: {
    label: 'Jazz / Soul',
    mark: 'JAZZ',
    sub: 'warm + smooth',
    audio: {
      tempo: 0.95,
      lowpass: 10000,
      highpass: 40,
      reverbWet: 0.35,
      bassGain: 2,
      midGain: 2,
      highGain: -1,
      distortion: 0,
      vinyl: 0.04,
      compression: 0.3,
    },
    visual: { feedbackAlpha: 0.94, modeOrder: ['Water', 'Waveform Rings', 'Sand', 'Spectral Lattice', 'Radial Bars', 'Wave Terrain', 'Plasma Orb', 'Prism Void'] },
    pitchLock: true,
    pitchReason: 'On recommended. A small tempo nudge should keep the vocal character intact.',
  },
  gothic: {
    label: 'Dark / Gothic',
    mark: 'DARK',
    sub: 'cavernous + slow',
    audio: {
      tempo: 0.75,
      lowpass: 5500,
      highpass: 70,
      reverbWet: 0.7,
      bassGain: 3,
      midGain: -2,
      highGain: -5,
      distortion: 0.1,
      vinyl: 0,
      compression: 0.2,
    },
    visual: { feedbackAlpha: 0.97, modeOrder: ['Prism Void', 'Plasma Orb', 'Waveform Rings', 'Water', 'Sand', 'Spectral Lattice', 'Wave Terrain'] },
    pitchLock: false,
    pitchReason: 'Off recommended. The deep pitch-down is part of the darker, cavernous feel.',
  },
  cinematic: {
    label: 'Orchestral / Cinematic',
    mark: 'FILM',
    sub: 'hall reverb + wide',
    audio: {
      tempo: 0.9,
      lowpass: 14000,
      highpass: 30,
      reverbWet: 0.6,
      bassGain: 2,
      midGain: 1,
      highGain: 1,
      distortion: 0,
      vinyl: 0,
      compression: 0.25,
    },
    visual: { feedbackAlpha: 0.95, modeOrder: ['Spectral Lattice', 'Wave Terrain', 'Waveform Rings', 'Plasma Orb', 'Water', 'Prism Void', 'Sand', 'Kaleidoscope'] },
    pitchLock: true,
    pitchReason: 'On recommended. Natural pitch lets the hall reverb sell the scale.',
  },
};

export const DEFAULT_AUDIO_PARAMS = { ...VIBES.neutral.audio };
